"""Terminal UI display module for Stella using the Rich library.

Provides styled rendering of welcome banners, dynamic confidence progress bars,
stylist messages, recommendations, state dumps, and graceful user input handling.
"""

from __future__ import annotations

from rich import box
from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.prompt import Prompt
from rich.text import Text

# Module-level Console singleton
console: Console = Console()


def display_welcome() -> None:
    """Display a warm, styled welcome banner introducing Stella and the consultation process."""
    welcome_text = Text()
    welcome_text.append("✨ Welcome! I'm Stella, your personal dress styling advisor.\n\n", style="bold deep_pink3")
    welcome_text.append(
        "I will guide you through a thoughtful 4-question consultation to determine your ideal dress size, "
        "flattering silhouettes, and personalized brand recommendations:\n\n",
        style="white",
    )
    welcome_text.append("  1. Measurements & Size History\n", style="cyan")
    welcome_text.append("  2. Fit Preferences & Body Silhouette\n", style="cyan")
    welcome_text.append("  3. Style Aesthetic & Event Occasion\n", style="cyan")
    welcome_text.append("  4. Past Purchase Success & What Fit Well\n\n", style="cyan")
    welcome_text.append(
        "Along the way, our styling confidence meter will update in real-time as we learn more about you.",
        style="italic dim",
    )

    panel = Panel(
        welcome_text,
        title="[bold magenta]✨ Stella · AI Dress Styling Advisor ✨[/bold magenta]",
        subtitle="[dim]Personalized Sizing & Silhouette Recommendations[/dim]",
        border_style="deep_pink3",
        box=box.ROUNDED,
        padding=(1, 2),
    )
    console.print()
    console.print(panel)
    console.print()


def display_confidence_bar(confidence: float, step: int) -> None:
    """Render a static confidence progress bar and current step indicator.

    Args:
        confidence: Confidence score as a percentage (0.0 to 100.0).
        step: Current consultation step number (1 to 4).
    """
    clamped_conf = max(0.0, min(100.0, float(confidence)))
    rounded_conf = int(round(clamped_conf))

    # Color coding: red (0-30), yellow (31-60), green (61-100)
    if rounded_conf <= 30:
        color_style = "red"
    elif rounded_conf <= 60:
        color_style = "yellow"
    else:
        color_style = "green"

    bar_width = 20
    filled_blocks = int(round((clamped_conf / 100.0) * bar_width))
    filled_blocks = max(0, min(bar_width, filled_blocks))
    empty_blocks = bar_width - filled_blocks

    bar_text = Text()
    bar_text.append(f"Step {step}/4  •  ", style="bold cyan")
    bar_text.append("Confidence: [", style="dim white")
    bar_text.append("█" * filled_blocks, style=f"bold {color_style}")
    bar_text.append("░" * empty_blocks, style="dim white")
    bar_text.append(f"] {rounded_conf}%", style=f"bold {color_style}")

    panel = Panel(
        bar_text,
        border_style=color_style,
        box=box.ROUNDED,
        padding=(0, 1),
        expand=False,
    )
    console.print(panel)


def display_stella_message(message: str) -> None:
    """Display a response or question from Stella formatted with Markdown.

    Args:
        message: The text or markdown content generated by Stella.
    """
    console.print()
    console.print(Text("✨ Stella:", style="bold deep_pink3"))
    console.print(Markdown(message))
    console.print()


def get_user_input(prompt_text: str = "[bold cyan]You[/bold cyan] > ") -> str:
    """Prompt the user for input with interrupt and EOF handling.

    Args:
        prompt_text: The styled prompt string to display.

    Returns:
        The stripped input string entered by the user, or an empty string on EOF/interrupt.
    """
    try:
        user_input = console.input(prompt_text)
        return user_input.strip()
    except (KeyboardInterrupt, EOFError):
        console.print()
        display_goodbye()
        return ""


def display_recommendation(recommendation: str, confidence: float) -> None:
    """Display the final styling and size recommendation inside a highlighted panel.

    Args:
        recommendation: The markdown recommendation text from Stella.
        confidence: The final confidence score percentage (0.0 to 100.0).
    """
    clamped_conf = max(0.0, min(100.0, float(confidence)))
    rounded_conf = int(round(clamped_conf))

    if rounded_conf <= 30:
        conf_style = "red"
    elif rounded_conf <= 60:
        conf_style = "yellow"
    else:
        conf_style = "green"

    panel = Panel(
        Markdown(recommendation),
        title="[bold magenta]👗 Stella's Tailored Dress Recommendation 👗[/bold magenta]",
        subtitle=f"[{conf_style}]Final Confidence Score: {rounded_conf}%[/{conf_style}]",
        border_style="deep_pink3",
        box=box.DOUBLE,
        padding=(1, 2),
    )
    console.print()
    console.print(panel)
    console.print()


def display_state_dump(dump: str) -> None:
    """Display the current session state dump in a muted inspector panel.

    Args:
        dump: The formatted string dump of the session state.
    """
    panel = Panel(
        Text(dump, style="dim white"),
        title="[dim]🔍 Session State[/dim]",
        border_style="dim",
        box=box.ROUNDED,
        padding=(1, 2),
    )
    console.print()
    console.print(panel)
    console.print()


def display_error(message: str) -> None:
    """Display an error message styled in red.

    Args:
        message: The error description to display.
    """
    panel = Panel(
        Text(f"❌ {message}", style="bold red"),
        title="[bold red]Error[/bold red]",
        border_style="red",
        box=box.ROUNDED,
        padding=(0, 1),
    )
    console.print()
    console.print(panel)
    console.print()


def display_goodbye() -> None:
    """Display a styled farewell message when the session ends."""
    goodbye_text = Text(
        "Thank you for consulting with Stella. Wishing you impeccable style! ✨",
        style="italic deep_pink3",
    )
    panel = Panel(
        goodbye_text,
        title="[bold magenta]✨ Goodbye ✨[/bold magenta]",
        border_style="magenta",
        box=box.ROUNDED,
        padding=(0, 2),
    )
    console.print()
    console.print(panel)
    console.print()


__all__ = [
    "console",
    "display_confidence_bar",
    "display_error",
    "display_goodbye",
    "display_recommendation",
    "display_state_dump",
    "display_stella_message",
    "display_welcome",
    "get_user_input",
]
